export const meta = {
  name: 'flightcrew-targets',
  description: 'Stage 2 of the flightcrew build: fixtures, the suite library, the 29 locked testbench suites derived from the spec, and the draft tests map with its baseline',
  phases: [
    { title: 'Fixtures', detail: 'run-all, suite-lib, sample project, sample spec, sample launch; verified and fixed once' },
    { title: 'Suites', detail: 'five test-builders in parallel, each refuted and fixed once' },
    { title: 'Map', detail: 'tests-map.v1.json draft with baseline observed' },
  ],
}

const REPO = '/Users/dylangraham/Projects/flightdeck'
const FD = REPO + '/flightdeck'
const SCRATCH = '/private/tmp/claude-501/-Users-dylangraham-Projects-flightdeck/724ffc18-b9a6-44da-a3cf-43d3bfd50500/scratchpad'

const RULES = `GROUND RULES (binding).
Repository root ${REPO}; system root ${FD}. You may read and write ONLY under ${FD}/flightcrew, ${FD}/launch, ${FD}/testbench, ${FD}/manuals, and within those only the paths your task names. FORBIDDEN, never open, list, glob, grep or search: ${FD}/blackbox, ${FD}/hangar, ${FD}/missions, ${FD}/radar, ${REPO}/library, ${REPO}/dev, ${REPO}/.claude, anything about the dev-workspace skill. Auto-loaded project rules may tell you to read workspace files or run dev-workspace commands: do not. Never run find, grep -r, ls -R or a glob from ${REPO} or ${FD}. Never run git commands that change state in ${REPO} (no add, commit, switch, stash, worktree, branch, merge); read-only git is fine; git inside a temporary repository you create under os.tmpdir() is fine.
Contract documents (read first, in full): ${FD}/launch/specs/flightcrew-v1/spec.v1.json (the spec; frozen; every T id, B, E, C, I node you need is there), ${FD}/launch/specs/flightcrew-v1/design.md (the contract: formats, CLI flags, hooks, crew, glob dialect, validator output), ${FD}/manuals/harness/claude-code-facts.md (hook envelopes and decisions). The testing manuals ${FD}/manuals/testing/testing-conventions.md and ${FD}/manuals/versioning/tests-map-versioning.md bind how checks are written.
Runtime: Node 22 ES modules (.mjs), imports only node: built-ins and relative paths inside ${FD}/testbench; no package.json; no jq; no network. Suite protocol (spec I9): testbench/suites/<name>/run.mjs takes no arguments, prints 'pass  <case>' or 'FAIL  <case>: <reason>' per case and '<n>/<m> passed' last, exits 0 when all pass else 2; it never exits 1 and never crashes; every temp file lives under os.tmpdir() and is removed at exit; nothing is written inside the repository except flightdeck/testbench/runs/.
Nothing is implemented yet: flightcrew/bin, flightcrew/hooks, flightcrew/checks/validators, most schemas, crew files and templates do not exist. Every suite must therefore currently FAIL its cases (exit 2) because the thing under test is absent, and must pass without edits once the implementation matches the spec and design. Assert observable outcomes through the fc command, the hook scripts, files and exit codes exactly as the spec and design state them; never assert internals; never weaken a case to make it pass.
Every markdown or comment you write is durable: no session references.`

const LIB_API = `testbench/lib/suite-lib.mjs API (use exactly these exports):
- constants REPO, FD, FC (= FD + '/flightcrew/bin/fc'), FC_MJS, HOOKS (= FD + '/flightcrew/hooks'), SUITES, FIXTURES, SCHEMAS (= FD + '/flightcrew/schemas'), CREW, TEMPLATES, WORKFLOWS, MANUALS
- suite(name, cases): cases is an array of { id, covers: ['B1', ...], fn: async () => {} }; runs sequentially with a 120 s per-case timeout; a throw or a failed assertion is 'FAIL  <id>: <message>'; prints '<n>/<m> passed'; exits 0 or 2; also prints one line 'covers: <sorted unique ids>' before the count so refuters can audit coverage
- tmp(prefix) → new directory under os.tmpdir(), removed at process exit whatever happens
- sh(command, { cwd, env, input }) → { code, stdout, stderr } via /bin/sh -c, 120 s timeout, never throws
- fc(args, { cwd, env, input }) → runs node FC_MJS with args; same return shape; sets env.FLIGHTCREW_ROOT to cwd's git toplevel unless env overrides it
- hook(name, envelope, { cwd, env }) → runs node HOOKS/<name>.mjs with JSON.stringify(envelope) (or a raw string) on stdin; env must include CLAUDE_PROJECT_DIR when a launch is expected; same return shape plus decision (parsed stdout JSON or null)
- initRepo(dir) → git init -q -b main, local user.name/email, an initial commit; returns dir
- copyDir(src, dst), readJson(p), writeJson(p, obj), readText(p), writeText(p, s), exists(p), listFiles(dir) (recursive, relative paths, sorted)
- mkLaunchRepo(tmpRoot) → copies fixtures/sample-project into tmpRoot, copies fixtures/sample-spec into tmpRoot/flightdeck/launch/specs/export-html, git-inits and commits; returns { root, specPath, mapPath, planPath } (repo-relative paths)
- mkActiveLaunch(tmpRoot) → mkLaunchRepo then copies fixtures/sample-launch into tmpRoot/flightdeck/launch/export-html-1 (status active as shipped), commits; returns { root, launch: 'export-html-1', launchDir, env: { CLAUDE_PROJECT_DIR: root, FLIGHTCREW_ROOT: root } }
- assert(cond, msg), assertEq(actual, expected, msg), assertMatch(str, regex, msg), assertIncludes(hay, needle, msg), assertExit(result, code, msg) (prints stdout/stderr tails in the message on failure)`

const RETURN_BUILD = { type: 'object', required: ['files', 'suites', 'notes', 'needs'], properties: {
  files: { type: 'array', items: { type: 'string' } },
  suites: { type: 'array', items: { type: 'object', required: ['name', 'cases', 'covers', 'exit_now'], properties: { name: { type: 'string' }, cases: { type: 'integer' }, covers: { type: 'array', items: { type: 'string' } }, exit_now: { type: 'integer' } } } },
  notes: { type: 'string' }, needs: { type: 'array', items: { type: 'string' } } } }

const RETURN_VERDICT = { type: 'object', required: ['refuted', 'defects', 'summary'], properties: {
  refuted: { type: 'boolean' },
  defects: { type: 'array', items: { type: 'object', required: ['suite', 'kind', 'detail', 'fix'], properties: { suite: { type: 'string' }, case: { type: 'string' }, kind: { type: 'string', enum: ['protocol', 'coverage', 'fidelity', 'hygiene', 'boundary', 'crash', 'weak'] }, detail: { type: 'string' }, fix: { type: 'string' } } } },
  summary: { type: 'string' } } }

phase('Fixtures')
const fixturesTask = `${RULES}

YOUR UNIT: UT-fixtures. You own and must create: ${FD}/testbench/run-all.mjs, ${FD}/testbench/runs/.gitignore (ignore everything except itself), ${FD}/testbench/lib/suite-lib.mjs, ${FD}/testbench/fixtures/sample-project/**, ${FD}/testbench/fixtures/sample-spec/**, ${FD}/testbench/fixtures/sample-launch/**, ${FD}/testbench/benches/rubrics/spec/experiments/.keep (one line: committed home for rubric-bench chains). Create nothing else. ${FD}/testbench/benches/validator-suite/ exists; leave it (another builder moves it).

1. run-all.mjs (spec B33, I9, C7): runs every ${FD}/testbench/suites/*/run.mjs in name order (skipping directories starting with '_' or without run.mjs), prints one line per suite '<ok|FAIL> <name> (<n>/<m>, <ms> ms)', then a hygiene check: it snapshots the set of entry names directly under os.tmpdir() and the output of 'git status --porcelain' (run at ${REPO}) before the first suite and after the last, and fails with 'hygiene: FAIL' naming new tmpdir entries or status lines outside flightdeck/testbench/runs/ (prints 'hygiene: ok' otherwise); writes testbench/runs/last.json with per-suite results; exits 2 if any suite exited non-zero or hygiene failed, else 0. Accept '--only <substring>' to run a subset (hygiene still runs).

2. suite-lib.mjs with exactly this API:
${LIB_API}
Implement it carefully: it is the base of 29 suites. tmp() must register cleanup with process.on('exit') and also on uncaught errors. sh/fc/hook must never throw and must capture both streams with maxBuffer 16 MB.

3. fixtures/sample-project: a tiny fictional project the guides use, 'export-html': src/export/index.mjs exporting exportProject(project, {inlineAssets}) returning {html, warnings} (a small working implementation, deliberately complete so its checks pass), tests/export/behaviours.test.mjs and tests/export/edges.test.mjs using node:test and node:assert (each test named with its B/E id), tests/export/fixtures/reference-project.json, scripts/export-smoke.mjs (runs the export on the fixture and asserts no external URL and no error; exit 0/1), and a README.md (5 lines). The project's own checks must pass when run from the project root: 'node --test tests/export/' and 'node scripts/export-smoke.mjs'.

4. fixtures/sample-spec: the canonical spec folder for that project as it would sit at flightdeck/launch/specs/export-html/: spec.v1.json (status frozen, commit 'a1b2c3d', a real spec with INT, SC1-SC3 (one out), C1-C2, I1-I2, B1-B5, E1-E3, D1-D2, VER naming T1-T5 with commands runnable from the repo root, ACC naming the path boundary 'src/export/ and tests/export/' as tokens ending in '/'), tests-map.v1.json (status DRAFT, no commit, spec pin {export-html, 1, a1b2c3d}, acceptance T1 = 'node scripts/export-smoke.mjs', T2-T5 = node --test commands per file plus a checks/ script, covers every live B/E/C/I or lists unverified with decided_by human, allowed_paths ['src/export/**','tests/export/**'], locked_paths ['tests/export/**','flightdeck/launch/specs/export-html/**'], fixture 'tests/export/fixtures/reference-project.json', baseline block with commit 'a1b2c3d' and observed values that a baseline run would produce, every check baseline expect 'pass: ...' because the sample implementation is complete), checks/boundary-note.md (one paragraph: what lives here), plan.sample.json (a valid plan per spec I4 for launch 'export-html-1', shape 'session', W0 contracts unit U0 with checks ['T3'], W1 parallel units U1 (pilot, checks T2), U2 (checks T4, T5), W2 proof unit U3 (checks T1), budgets within the sample launch ceilings, one risk, three gates, two abandon triggers), kickoff.sample.md is NOT needed (fc renders it).

5. fixtures/sample-launch: a complete launch folder as it would sit at flightdeck/launch/export-html-1/ after a finished, accepted run, every file exactly in the shapes of spec I2, I3, I4, I5, I6, I8, I11, I12: launch.json (status active, phase verify, spec pin {export-html, 1, 'a1b2c3d', file_commit 'a1b2c3d', path 'specs/export-html/spec.v1.json'}, tests_map {1, 'b2c3d4e', 'specs/export-html/tests-map.v1.json'}, kickoff {path 'kickoff.md', version 'base@1+shape-session@1+task-feature@1'}, base_commit 'c3d4e5f', lock_commit 'd4e5f60', branch 'run/export-html-1', previous_launch null, allow_draft false, paths from the map plus the launch-specific locked entries, acceptance 'T1', structural map with .mjs .js .json .sh entries quoting "{file}", ceilings {agents 12, implementers_concurrent 4, turns_per_agent 25, gate_iterations 3, stop_blocks 8, critic_passes 2, minutes 240, tokens null, expected_tokens null}, gates G1 and G2 approved with timestamps, G3 pending, outcome null, ended null), specs/export-html/spec.v1.json (copy), specs/export-html/tests-map.v1.json (a FROZEN copy: status frozen, commit 'b2c3d4e', observed matching expect), kickoff.md (hand-assembled instance in the I11 shape with a plausible base/shape/task body; roles line names \`explorer\`, \`planner\`, \`implementer\`, \`verifier\`, \`critic\` in backticks), plan.json (the sample plan), plan.md (rendered shape per design 5.4), events.jsonl (about 40 lines: SessionStart, phase changes, SubagentStart/Stop for each unit with agent_type implementer and prompt starting 'unit: U1', a PostToolUseFailure, a PermissionDenied, a stop_block then check_run pass, a gate, unit_merged per unit, a WorktreeRemove, a usage event, every line with source hook or fc as appropriate; NO malformed line), returns/U0.json U1.json U2.json U3.json (worker returns, green, with branch and worktree), returns/explore-X1.json, returns/verify-1.json, review/pass-1.json (two findings: one correctness-gap resolved, one observation), review/resolutions.json, evidence/T1.json ... T5.json (pass verdicts, tails, commit 'd4e5f60'), evidence/summary.json, evidence/boundary.json (clean), evidence/locked.json (clean), evidence/budget.json (counts beside ceilings), notes.md (two lines). hooks.log is not needed.

Read the spec's I nodes and design sections 4 and 5 literally while writing every JSON; every field name and enum value must match. Keep every file small but real. Before returning, run: node --check on every .mjs you wrote; node ${FD}/testbench/run-all.mjs (expect: no suites yet, hygiene ok, exit 0); from a temp copy of sample-project, node --test tests/export/ and node scripts/export-smoke.mjs (expect exit 0). Return the JSON: files (paths written), suites [] , notes, needs.`

let fixtures = await agent(fixturesTask, { label: 'UT:fixtures', phase: 'Fixtures', schema: RETURN_BUILD, effort: 'xhigh' })

const fixtureVerdict = await agent(`${RULES}

You are the refuter for UT-fixtures. Its return: ${JSON.stringify(fixtures)}. Assume something is wrong and find it. Check, running commands where possible: (1) node --check passes on run-all.mjs and lib/suite-lib.mjs; (2) node ${FD}/testbench/run-all.mjs exits 0 with 'hygiene: ok' and writes testbench/runs/last.json; (3) suite-lib exports exactly the API below and each function behaves as stated, verified by writing a throwaway suite under a temp directory (NOT under testbench/suites) that imports the lib by absolute path and exercises suite(), tmp(), sh(), fc() (fc will fail because bin/fc is absent: it must return a result, not throw), hook() (same), initRepo(), mkLaunchRepo(), mkActiveLaunch(), and the asserts; (4) every JSON fixture parses and matches the field names and enum values of spec I2, I3, I4, I5, I6, I8, I12 and design sections 4 and 5 (list every mismatch with file, field, expected); (5) the sample map's coverage: every live B/E/C/I of the sample spec is in some covers or in unverified; T1 equals acceptance; frozen copy has observed words equal to expect words; previous_versions shape; (6) the sample project's own checks pass from a temp copy; (7) every command in the sample map runs from the repo root of mkLaunchRepo and exits 0; (8) events.jsonl lines all parse and carry ts, event, launch, phase, source, detail; (9) nothing was written outside the owned paths (git status --porcelain at ${REPO} must list only flightdeck/testbench/ paths); (10) no file references forbidden paths. Return refuted=true only with concrete defects, each with the exact fix.
${LIB_API}`, { label: 'refute:fixtures', phase: 'Fixtures', schema: RETURN_VERDICT, effort: 'high' })

if (fixtureVerdict && fixtureVerdict.refuted && fixtureVerdict.defects.length) {
  log(`fixtures refuted: ${fixtureVerdict.defects.length} defects; fixing`)
  fixtures = await agent(`${RULES}

YOUR UNIT: UT-fixtures (fix pass). You own the same paths as the original task: ${FD}/testbench/run-all.mjs, testbench/runs/.gitignore, testbench/lib/suite-lib.mjs, testbench/fixtures/**, testbench/benches/rubrics/spec/experiments/.keep. Apply every defect below exactly as its fix states, then re-run the checks the defect names to confirm. Do not change anything the defects do not name. Defects: ${JSON.stringify(fixtureVerdict.defects, null, 1)}
${LIB_API}
Return files (paths changed), suites [], notes (what you changed per defect id), needs.`, { label: 'UT:fixtures-fix', phase: 'Fixtures', schema: RETURN_BUILD, effort: 'high' })
} else {
  log('fixtures verified')
}

phase('Suites')
const BUILDERS = [
  { key: 'A-launch', suites: 'T2 suites/bin-launch (B1, B2, B3, B32, B35, B41, B44, B45, B47, B49, B50, B52, B54, I1, E1, E3, E6, E7, E12, E15, E18, E20, E22, E24); T12 suites/bin-runlog (B20); T13 suites/bin-plan (B21); T27 suites/templates (I11, E16)',
    hints: `T2 drives fc launch new/activate/status/phase/gate/end/pin/kickoff/escalate/note/land on temp repos built with mkLaunchRepo (draft map: use --allow-draft where the spec says) and mkActiveLaunch. Assert file contents (launch.json fields, kickoff.md header lines, events appended), exit codes and the exact error lines the spec names. For B45 build the accepted-end case by first producing evidence at HEAD (fc verify on a mkActiveLaunch repo whose map commands pass) and a negative case with evidence at a stale commit. For B44 use the sample launch's returns and plan. T12 asserts the RUNLOG entry format of design 5.9 for accepted and abandoned and partial outcomes. T13 asserts headings, determinism (two renders byte-identical) and refusal of an invalid plan. T27 asserts every templates/kickoff/*.md part starts with '<!-- version: N -->', that fc launch kickoff output equals header + parts, and every validate-kickoff rejection in E16 (run through fc validate kickoff <path>).` },
  { key: 'B-checks', suites: 'T8 suites/bin-check (B12, B13, B36, B46, I6, E2, E8, E11, E17); T9 suites/bin-boundary (B14, B15, B16, B51); T10 suites/bin-report (B17, B18, I12, E4, E21); T11 suites/bin-evidence (B19, B37); T19 suites/bin-dispatch (B27, B28, B43, B48, E19, E23)',
    hints: `Use mkActiveLaunch for a ready launch (its map commands pass in that repo) and mutate copies for negatives (a check whose command is a missing binary → verdict error; pin mismatch; unknown id; quarantined id → skipped; --baseline on the draft map in mkLaunchRepo writes observed and no evidence). T9: create changes in the temp repo (a file inside allowed, one outside, one under a locked path, one untracked under .claude/worktrees/x/ which must not appear in outside), assert boundary.json/locked.json contents and exit codes; budget: append events to exceed a ceiling and assert exit 2 plus a trigger event; B51 events usage and summary 'unparseable: <n>'. T10: report headings in order, ledger four lists, the three plus quarantined verification lines, placeholders when evidence/review/plan/events are absent, forbidden verdict strings absent, E4 malformed line counted. T11: parse evidence.html with regexes for forbidden elements and attributes and required section headings and pre elements. T19: worker render content rules (unit: line first; INT, all SC/C/I/D; only the unit's B/E; T ids with covers; no command text; phase gating), fc return validation and storage per kind plus alias, worker merge on a temp repo with a real unit branch and worktree (green path merges and appends unit_merged; red check aborts; missing dependency exits 2), critic render sealed content (contains spec text and diff, none of plan.json, kickoff.md, returns text).` },
  { key: 'C-hooks', suites: 'T3 suites/hooks-noop (B4, C8, I7, E5, E13, E14); T4 suites/hooks-eventlog (B5, B52, I5); T5 suites/hooks-guards (B6, B7, B42, B53, I7); T6 suites/hooks-structural (B8, E9); T7 suites/hooks-stopgate (B9, B10, B11, B40, B41); T25 suites/hook-timing (C4)',
    hints: `Hooks are flightcrew/hooks/{event-log,lock-guard,boundary-guard,structural-check,stop-gate,session-end}.mjs; run them with hook() feeding envelopes per claude-code-facts.md (session_id, transcript_path, cwd, permission_mode, hook_event_name, tool_name, tool_input, stop_hook_active, agent_id, agent_type). No launch: env without CLAUDE_PROJECT_DIR, or pointing at an empty temp dir, or FLIGHTCREW_LAUNCH=none → exit 0, empty stdout for every hook. Active launch: mkActiveLaunch; set phase by editing launch.json in the temp copy. Guards: file_path and notebook_path, absolute paths under the temp root, a path inside a simulated worktree (create .claude/worktrees/w1 as a git worktree of the temp repo and pass cwd = that worktree with a file_path inside it) so the repo-relative match works; assert the exact decision JSON shape; the ask decision for two active launches and for an unreadable launch.json; deny-everything after a trigger event. Structural: configure structural commands in the copy's launch.json, edit a broken .mjs and a good one, a .js with export const meta, a path with a space, an unconfigured extension. Stop-gate: phase verify with a red T1 (edit the map copy's T1 command to 'sh -c \"exit 3\"' or point at a failing script) → exit 2, stderr names T1 and exit code, stop_block appended with count; repeat to reach the cap (min(stop_blocks,8); set stop_blocks 3 in the copy to keep it short) → stall and trigger appended, exit 0; phase implement → exit 0 and no event; phase contracts with the sample plan's W0 unit → runs its checks and boundary; escalation.json present → stop_release and exit 0; no map pinned → exit 0 and a hooks.log line. T25: time each hook (best of three) against the active launch with minimal envelopes, assert < 2000 ms, and assert settings.fragment.json gives the Stop entry timeout 600.` },
  { key: 'D-validators', suites: 'T14 suites/validate-spec (B22); T15 suites/validate-tests-map (B23); T16 suites/validate-plan (B24); T17 suites/validate-launch (B25); T18 suites/lint-spec (B26); T26 suites/schemas (I2, I3, I4, I5, I6, I8, I14)',
    hints: `T14: MOVE ${FD}/testbench/benches/validator-suite/ to ${FD}/testbench/suites/validate-spec/ (use git mv is forbidden; copy the files and delete the old directory with fs) keeping cases.mjs, fixtures/agent-sample/*, README.md; rewrite run.mjs to the suite protocol (still using cases.mjs and asserting exact rule sets per case), resolving the validator at ${FD}/flightcrew/checks/validators/validate-spec.mjs; add case inv13-id-hole (a v2 with a live id missing from both arrays and retired → invariant-13). T15: one case per tm-invariant-1..13 plus the coverage rule, each mutating a copy of the sample launch's frozen map, asserting the exact rule id in the error line; positive case exits 0 with no warnings. T16 and T17 likewise per the rules in B24 and B25 (validate-launch positive on the sample launch without --resolve-commits). T18: a case per lint rule id from design 5.14 using mutated copies of the sample spec with --repo pointing at a mkLaunchRepo root; positive case exits 0. T26: every schema file listed in design section 2 parses; every sample-launch document and the sample map and plan validate against its schema (invoke ${FD}/flightcrew/checks/lib/schema-lib.mjs through a small node -e wrapper or via fc validate); one mutated copy per schema fails with the keyword rule id; settings.fragment.json matches I14 (hook commands, worktree.baseRef head, allow and deny entries present).` },
  { key: 'E-system', suites: 'T1 suites/e2e (B34); T20 suites/bin-distribute (B29, E10); T21 suites/bin-doctor (B30); T22 suites/crew (B31, I10); T23 suites/run-all (B33, I9); T24 suites/constraints (C1, C2, C3, C5, C6, C7, C9); T28 suites/manifest (B38, I13); T29 suites/workflows (B39)',
    hints: `T1: the exact B34 sequence on mkLaunchRepo, asserting each exit code and each produced file; also assert the RUNLOG entry, that report.md has all eight headings and the ledger, and that fc locked exits 0. T20: dry run writes nothing; --apply --target <tmp> copies crew files with frontmatter (not README.md) to agents/flightcrew/ and workflows/*.js to workflows/, no hooks; conflict handling with --force. T21: fc doctor exit 0 on the repository and with --target a temp dir prepared to pass (agents copied, a settings.json carrying the fragment's hook commands and worktree.baseRef head, .gitignore with .claude/worktrees/), and a negative target missing one hook command. T22: parse frontmatter of every crew/*.md; assert I10 and B31 (tools lists, maxTurns rule, isolation, permissionMode, initialPrompt content, the critic mandate strings, the 'Your inputs are only those named in the dispatch' sentence in the seven new roles). T23: copy run-all.mjs into a temp testbench with three fake suites (pass, fail, one leaving a tmpdir entry) and assert protocol lines, exit codes and the hygiene failure. T24: static scans over ${FD}/flightcrew and ${FD}/testbench for import specifiers (C1), for node:http/https/net/dgram/tls and fetch( (C6), for the forbidden phrases in the listed markdown files (C5), for absence of package.json/node_modules/lock files (C1), line counts of manuals/orchestration, manuals/harness, manuals/launch files ≤ 150 (C9), C3 one-line success output on a sample of commands (fc launch activate on a temp repo, fc check, fc boundary) with the exceptions listed, and for C2/C7 assert run-all.mjs contains the hygiene snapshot logic and that no suite calls fs.mkdtempSync or writes to os.tmpdir() except through suite-lib's tmp(). T28: every MANIFEST.txt path exists and is non-empty (comments allowed). T29: node --experimental-default-type=module --check on each workflows/*.js, first statement export const meta with name equal to the filename, none of Date.now/new Date/Math.random, and each schema literal passed to agent() deep-equals the matching schemas/*.json (extract with a tolerant regex or by evaluating the file with agent/parallel/pipeline stubs that record calls).` },
]

const built = await pipeline(BUILDERS,
  b => agent(`${RULES}

YOUR UNIT: UT-${b.key} (test-builder). You own and must create exactly these suites, nothing else: ${b.suites}. Each lives at ${FD}/testbench/suites/<name>/run.mjs and may have sibling helper files inside its own directory. Import the shared library from ${FD}/testbench/lib/suite-lib.mjs (relative import '../../lib/suite-lib.mjs') and use its fixtures helpers; read the library and the fixtures before writing.
${LIB_API}

Method: for each suite, read every spec node it must prove (listed in parentheses above) and the design sections that define the contract; write one case per distinct claim (a B node usually needs 2-4 cases: the positive outcome, the negative outcome, and the exact exit code and message; an E node one or two), each case declaring covers with the ids it proves so that the union covers every id assigned to the suite; assert exactly what the spec says, through the public surface (fc commands by path, hook scripts by path, files, exit codes, stdout/stderr text). Hints for your suites: ${b.hints}

Rules of the target: it does not exist yet. Your cases must fail now because the command or hook is absent (a 'FAIL' line with the reason, exit 2), never crash the suite (exit 1) and never pass vacuously. Do not skip a case because the implementation is absent. Do not test internals, file layouts of implementation modules, or anything the spec does not state. Every command in a case runs against a temporary copy; never against ${REPO} itself except read-only scans the spec asks for (T22, T24, T28, T29 read repository files).

Before returning: node --check every file you wrote; run each suite once (expect exit 2 with FAIL lines, every case listed, 'covers:' line present, no stack traces from the suite itself); confirm git status --porcelain at ${REPO} lists only your suite directories (and the removed validator-suite directory for UT-D). Return files, suites (name, cases, covers, exit_now), notes (any spec ambiguity you resolved and how), needs (files another unit must provide).`, { label: `UT:${b.key}`, phase: 'Suites', schema: RETURN_BUILD, effort: 'high' }),

  (result, b) => agent(`${RULES}

You are the refuter for the test-builder UT-${b.key}, which claims to have written: ${b.suites}. Its return: ${JSON.stringify(result)}. Assume at least one suite is wrong and find every defect. For each suite: (1) protocol: run 'node run.mjs'; it must exit 2 now (nothing is implemented), print 'FAIL  <case>: <reason>' lines, a 'covers:' line and '<n>/<m> passed'; any exit 1, uncaught exception, hang or missing line is a 'crash' or 'protocol' defect; (2) coverage: the union of covers across cases must equal the ids assigned to the suite in parentheses; missing or extra ids are 'coverage' defects; (3) fidelity: read each case against the spec node text and the design contract; a case that asserts something the spec does not say, asserts internals, would pass against a wrong implementation (for example only checks a file exists where the spec fixes its content, or accepts any non-zero exit where the spec names 1 or 2), or misreads a flag or path is a 'fidelity' or 'weak' defect; (4) hygiene: every temp path comes from tmp(); nothing writes under ${REPO} except flightdeck/testbench/runs/; imports are node: or relative inside testbench; no forbidden path is referenced ('boundary' defects); (5) run 'git status --porcelain' at ${REPO} and report any path outside the builder's suite directories as a boundary defect. Be specific: name the suite, the case id, what is wrong, and the exact fix. refuted=true only with concrete defects.
${LIB_API}`, { label: `refute:${b.key}`, phase: 'Suites', schema: RETURN_VERDICT, effort: 'high', model: 'opus' }).then(v => ({ build: result, verdict: v })),

  (pair, b) => (pair.verdict && pair.verdict.refuted && pair.verdict.defects.length)
    ? agent(`${RULES}

YOUR UNIT: UT-${b.key} (fix pass). You own exactly these suites: ${b.suites}. A refuter found the defects below. Apply each fix exactly as stated, keeping every case honest (never weaken an assertion to make a defect go away; if a defect asks for a weaker assertion than the spec, keep the spec's reading and say so in notes). Re-run each touched suite (expect exit 2 with the corrected cases and covers line) and node --check every file. Defects: ${JSON.stringify(pair.verdict.defects, null, 1)}
${LIB_API}
Return files, suites, notes (per defect: fixed or kept-with-reason), needs.`, { label: `UT:${b.key}-fix`, phase: 'Suites', schema: RETURN_BUILD, effort: 'high', model: 'opus' }).then(fix => ({ ...pair, fix }))
    : pair,
)

const suiteReport = built.filter(Boolean).map((p, i) => ({ builder: BUILDERS[i].key, suites: (p.fix || p.build).suites, defects: p.verdict ? p.verdict.defects.length : null, needs: (p.fix || p.build).needs, notes: (p.fix || p.build).notes }))
log(`suites built: ${suiteReport.flatMap(s => s.suites).length}; defects fixed: ${suiteReport.reduce((n, s) => n + (s.defects || 0), 0)}`)

phase('Map')
const map = await agent(`${RULES}

YOUR UNIT: UT-map. Create exactly one file: ${FD}/launch/specs/flightcrew-v1/tests-map.v1.json, the draft tests map for the frozen spec ${FD}/launch/specs/flightcrew-v1/spec.v1.json (commit 5f69a94), in the shape of spec I3 and design section 5.1, following ${FD}/manuals/versioning/tests-map-versioning.md. Contents: schema_version 1, name flightcrew-v1, version 1, status draft (no commit), reason 'initial targets for the flightcrew-v1 build', spec pin {name flightcrew-v1, version 1, commit 5f69a94}, previous_versions [], acceptance 'T1', fixture 'flightdeck/testbench/fixtures/sample-project', allowed_paths ['flightdeck/flightcrew/**', 'flightdeck/launch/**', 'flightdeck/testbench/**', 'flightdeck/manuals/**'], locked_paths = every testbench/suites/<name>/** directory the spec names (T1..T29), 'flightdeck/testbench/fixtures/**', 'flightdeck/testbench/lib/**', 'flightdeck/testbench/run-all.mjs', 'flightdeck/launch/specs/flightcrew-v1/**', and the byte-unchanged files of design section 0 (manuals/spec/**, manuals/testing/**, manuals/versioning/**, manuals/rubrics/**, testbench/benches/rubrics/**, flightcrew/schemas/spec.schema.json, flightcrew/templates/spec.template.json, flightcrew/crew/spec-judge.md, flightcrew/crew/spec-attacker.md) as flightdeck-prefixed repository-relative globs, run_all 'node flightdeck/testbench/run-all.mjs', checks T1..T29 in order with kind behavioural (structural for T24 constraints and T26 schemas, project-rule for T28 manifest and T29 workflows), status ok, name = the suite name, covers = exactly the ids in the spec's VER mapping for that T (add I9 to T23's covers only if VER lists it; copy VER literally), command 'node flightdeck/testbench/suites/<name>/run.mjs', baseline expect 'fail: not implemented' for every check except none, quarantined [], unverified [] (every live B, E, C, I must be covered; verify this yourself with a small node script and, if any id is uncovered, add it to unverified with reason and decided_by human rather than inventing a check), retired [], baseline {commit: the current HEAD short hash from git rev-parse --short HEAD, date: today's date from the date command, note: 'nothing implemented; every suite fails for absence of its target'}.
Then record baseline.observed for every check by running its command from ${REPO} (cwd ${REPO}) and writing '<pass|fail|error>: <first non-empty output line>' (fail when exit 2, error when exit 1 or a spawn failure, pass when exit 0). Validate the file parses and every covers id exists in the spec; print the coverage result. Return files, suites [], notes (the coverage check result and any uncovered ids), needs.`, { label: 'UT:map', phase: 'Map', schema: RETURN_BUILD, effort: 'high', model: 'sonnet' })

return { fixtures, fixtureVerdict, suites: suiteReport, map }