#!/usr/bin/env node
// absorb.mjs — apply named fixes to a chain's draft. Fixes are keyed by finding so a chain applies only what its verdict named.
// Usage: node absorb.mjs <chain-dir> <fix>[,<fix>...]
// Fixes: c11 c2 i1 i6in i7in i8in retid i9disp i10names i10types probe sc12 B3 B4 B6 B9 B11 B13 B14 B15 B16 B23
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [dir, list] = process.argv.slice(2);
if (!dir || !list) { console.error('usage: node absorb.mjs <chain-dir> <fix,fix,...>'); process.exit(2); }
const p = join(dir, 'spec.v1.json');
const s = JSON.parse(readFileSync(p, 'utf8'));
const byId = (a, i) => a.find(n => n.id === i);
const rep = (node, a, b) => { if (!node.text.includes(a)) { console.error(`no match in ${node.id}: ${a.slice(0, 50)}`); process.exit(1); } node.text = node.text.replace(a, b); };
const ver = (a, b) => { if (!s.verification.text.includes(a)) { console.error(`no match in VER: ${a.slice(0, 50)}`); process.exit(1); } s.verification.text = s.verification.text.replace(a, b); };
const addB = t => { const id = 'B' + (s.behaviours.length + 1); s.behaviours.push({ id, status: 'ok', text: t }); return id; };
const addC = t => { const id = 'C' + (s.constraints.length + 1); s.constraints.push({ id, status: 'ok', text: t }); return id; };
const edge = (id, a, b) => rep(byId(s.edges, id), a, b);
const applied = [];

const FIX = {
  c11() { byId(s.constraints, 'C11').text = "The body carries a section headed for each of the nine domains, the spec conventions, the verification addendum rules and the versioning rules, and the agent reads none of those documents at session time."; ver('C11 checks/c11-no-standards-read.mjs;', 'C11 checks/c11-standards-encoded.mjs, the body contains the four headed sections and no Read in the transcript resolves to a standards document;'); },
  c2() { byId(s.constraints, 'C2').text = "node dev/orchestration/checks/spec-readiness-lint.mjs <draft> --repo <project root> exits 0 on the draft that any rubric-judge verdict sheet names, with every produced path declared via --deliverable."; },
  i1() { byId(s.interfaces, 'I1').text = "{ intention: string | draft_path: path (a spec file whose INT node is the intention), template_path: path, schema_path: path, project_root: path, run_folder: path (dev/workspace/runs/<spec-name>/), run_log_path?: path }."; },
  i6in() { rep(byId(s.interfaces, 'I6'), 'In: one question, the stage it serves (intent | scope | constraints | interfaces | behaviours | verification), optional scope paths.', 'In: { question: string, stage: intent | scope | constraints | interfaces | behaviours | verification, scope_paths?: [path] }.'); },
  i7in() { rep(byId(s.interfaces, 'I7'), 'In: draft path, nine-domains description path, verification addendum path when agent-shaped, rubric path.', 'In: { draft_path: path, rubric_path: path }.'); },
  i8in() { rep(byId(s.interfaces, 'I8'), 'In: draft path and project root only.', 'In: { draft_path: path, project_root: path } and nothing else.'); },
  retid() { rep(byId(s.interfaces, 'I6'), 'Out: { answer: string,', 'Out: { id: string (X<n>, assigned by the agent at dispatch), answer: string,'); rep(byId(s.interfaces, 'I5'), 'closed_by: node id | explorer return | provider | null', 'closed_by: { kind: node | return | provider, id: string } | null'); rep(byId(s.interfaces, 'I9'), 'ref: problem id | node id | reason', 'ref: { kind: problem | node | reason, value: string }'); },
  i9disp() { byId(s.interfaces, 'I9').text = "dev/workspace/runs/<spec-name>/interview/findings.json: { dispatches: [ { source: judge | attacker, draft_path: path, result: ready | returned | no findings | findings: integer } ], findings: [ { id: string, source: judge | attacker, state: asked | absorbed | rejected, ref: { kind: problem | node | reason, value: string } } ] }."; },
  i10names() { rep(byId(s.interfaces, 'I10'), 'unchecked_names: [],', 'unchecked_names: [ string (a path-shaped name exactly as written in the draft) ],'); },
  i10types() { byId(s.interfaces, 'I10').text = "Final fenced JSON block of the closing message: { draft_path: path, version: integer, counts: { B: integer, E: integer, C: integer }, nodes: { new: [string], changed: [string], retired: [string] }, validator: { exit: integer, errors: [string] }, linter: { exit: integer, failed: [string] }, judge: ready | returned | not run, attacker: no findings | findings: integer | not run, unchecked_names: [ string (a path-shaped name exactly as written in the draft) ], dispatches: [ { agent: string, stage: string, purpose: string } ], statement: string }; schema new at dev/orchestration/schemas/interviewer-handoff.schema.json, generated from this shape."; },
  probe() { ver('Checks pre-exist and are locked', 'Probe: at the gate the provider, not the builder, chooses one record from records/ and reads it; the record identifier is written to dev/orchestration/harness/spec-interviewer/records/probe.txt. Checks pre-exist and are locked'); s.acceptance.text = s.acceptance.text.replace('One probe transcript, chosen at the gate and not by the builder, has been read by the provider and its identifier recorded.', 'dev/orchestration/harness/spec-interviewer/records/probe.txt exists and names one record identifier present in records/.'); },
  sc12() { byId(s.scope, 'SC12').text = "Editing any project code or any file outside the paths the definition of done names; C6 is the boundary of the produced agent at run time, not of this work."; },
  B3() { byId(s.behaviours, 'B3').text = "[deterministic] The first draft file is written after the intent wave completes and before the first bundle file exists."; const n = addB("[deterministic] The first draft holds, in every domain, at least one node or the phrase 'empty by decision' with a reason."); edge('E17', '(boundary of B2, B21, B22)', `(boundary of B2, B21, B22, ${n})`); ver('B3 checks/b03-draft-before-bundle.mjs;', `B3 checks/b03-draft-before-bundle.mjs; ${n} checks/b${n.slice(1)}-domains-filled.mjs, the first draft file in the record has no empty domain without the phrase and a reason;`); },
  B4() { byId(s.behaviours, 'B4').text = "[deterministic] Every question belongs to exactly one bundle."; const n = addB("[deterministic] Every bundle's marker is the id of a register problem in state asked."); edge('E13', '(boundary of B4, B6', `(boundary of B4, ${n}, B6`); ver('B4 checks/b04-bundle-markers.mjs, every bundle marker resolves to a register problem in state asked and every question id is in one bundle;', `B4 checks/b04-question-in-one-bundle.mjs, every question id is in exactly one bundle; ${n} checks/b${n.slice(1)}-bundle-markers.mjs, every bundle marker resolves to a register problem in state asked;`); },
  B6() { byId(s.behaviours, 'B6').text = "[deterministic] An answer bundle that closes a problem produces the problem's node in the draft in the same turn."; const n = addB("[deterministic] An answer bundle that closes a problem sets that problem's state to closed with closed_by naming the node or the provider, in the same turn."); const c = addC("No bundle asks the provider to approve the text of a node already written."); edge('E2', '(boundary of B6)', `(boundary of B6, ${n}, ${c})`); edge('E13', 'B6)', `B6, ${n})`); ver('B6 checks/b06-node-same-turn.mjs;', `B6 checks/b06-node-same-turn.mjs; ${n} checks/b${n.slice(1)}-problem-closed-same-turn.mjs, every answered problem is closed with closed_by in the turn of the answer;`); ver('C12 checks/c12-bundle-size.mjs.', `C12 checks/c12-bundle-size.mjs; ${c} checks/c${c.slice(1)}-no-approval-questions.mjs, no question text asks for approval of a node id already present in the draft.`); },
  B9() { byId(s.behaviours, 'B9').text = "[deterministic] Every path-shaped name in the draft is matched by an explorer return with confidence certain and a pointer, or carries the marker (unchecked)."; const n = addB("[deterministic] Every name carrying the marker (unchecked) appears in the handoff's unchecked_names."); edge('E6', '(boundary of B9)', `(boundary of B9, ${n})`); ver('B9 checks/b09-names-cited.mjs;', `B9 checks/b09-names-cited.mjs; ${n} checks/b${n.slice(1)}-unchecked-listed.mjs, every (unchecked) marker in the draft has a matching entry in the handoff's unchecked_names;`); },
  B11() { byId(s.behaviours, 'B11').text = "[deterministic] Each failing judge question is entered in the findings ledger before the judge is dispatched again."; const n = addB("[deterministic] Each failing judge question either opens a register problem that is asked, or is absorbed into a named node, before the judge is dispatched again."); edge('E15', '(boundary of B10, B11)', `(boundary of B10, B11, ${n})`); ver('B11 checks/b11-judge-findings-ledger.mjs;', `B11 checks/b11-judge-findings-ledger.mjs; ${n} checks/b${n.slice(1)}-judge-findings-resolved.mjs, every ledger entry from the judge has a problem or node ref before the next judge dispatch;`); },
  B13() { byId(s.behaviours, 'B13').text = "[deterministic] Every attacker finding id appears in the findings ledger with exactly one state."; const n = addB("[deterministic] A rejected finding carries a reason in its ledger entry."); edge('E10', '(boundary of B12, B13, B18)', `(boundary of B12, B13, ${n}, B18)`); ver('B13 checks/b13-attacker-ledger.mjs;', `B13 checks/b13-attacker-ledger.mjs; ${n} checks/b${n.slice(1)}-rejected-has-reason.mjs, every rejected ledger entry has a non-empty reason;`); },
  B14() { byId(s.behaviours, 'B14').text = "[deterministic] The status becomes frozen with a commit only after a provider message instructing the freeze and node dev/workspace/filebox/validate-spec.mjs <draft> --for-freeze exiting 0."; const n = addB("[deterministic] The freeze commit contains only the spec file."); edge('E11', '(boundary of B14)', `(boundary of B14, ${n})`); ver('B14 checks/b14-freeze-on-instruction.mjs, including git show --stat of the freeze commit naming one file;', `B14 checks/b14-freeze-on-instruction.mjs; ${n} checks/b${n.slice(1)}-freeze-commit-one-file.mjs, git show --stat of the freeze commit names one file;`); },
  B15() { byId(s.behaviours, 'B15').text = "[deterministic] Given a frozen version file, new answers or findings produce the next version file per the versioning rules."; const n = addB("[deterministic] A frozen version file is byte-identical after any later session."); edge('E12', '(boundary of B15)', `(boundary of B15, ${n})`); ver('B15 checks/b15-revision.mjs, sha256 of the frozen file unchanged;', `B15 checks/b15-revision.mjs, a next version file exists after a post-freeze answer; ${n} checks/b${n.slice(1)}-frozen-unchanged.mjs, sha256 of the frozen file unchanged;`); },
  B16() { byId(s.behaviours, 'B16').text = "[deterministic] A session that receives a run folder with register problems not closed completes an explorer wave scoped to those problems' domains before any new problem is raised."; const n = addB("[deterministic] A session that receives a run folder with register problems not closed re-asks those problems' bundles before any new problem is raised."); rep(byId(s.decisions, 'D18'), 'B16, B17, B19 and B20', `B16, B17, B19, B20 and ${n}`); ver('B16 checks/b16-resume.mjs;', `B16 checks/b16-resume.mjs; ${n} checks/b${n.slice(1)}-resume-reask.mjs, every unclosed problem's bundle file is rewritten with state open before any new problem id appears;`); },
  B23() { byId(s.behaviours, 'B23').text = "[deterministic] An explorer candidate returned probable or guess becomes a register problem that is asked."; const n = addB("[deterministic] A candidate returned probable or guess appears in no node until its problem is answered."); edge('E7', '(boundary of B1, B21, B23)', `(boundary of B1, B21, B23, ${n})`); ver('B23 checks/b23-uncertain-candidates.mjs, no probable or guess candidate appears as a node before its problem is answered;', `B23 checks/b23-uncertain-candidates.mjs, every probable or guess candidate has an asked register problem; ${n} checks/b${n.slice(1)}-uncertain-quarantine.mjs, no probable or guess candidate appears as a node before its problem is answered;`); },
};

for (const f of list.split(',')) { if (!FIX[f]) { console.error('unknown fix: ' + f); process.exit(1); } FIX[f](); applied.push(f); }
writeFileSync(p, JSON.stringify(s, null, 2) + '\n');
console.log(`applied ${applied.join(', ')} → ${s.behaviours.length} B / ${s.constraints.length} C`);
